modLoader="javafml"
loaderVersion="[40]"
license="GPL-3.0-or-later"

[[mods]]
modId="vh_fortune_rebalance"
version="${file.jarVersion}"
displayName="VH Fortune Rebalance"
#logoFile="examplemod.png"
authors="PINPAL"
description='''
Remove Fortunate Expertise and add Fortune V to Vault Enchanter
'''

[[dependencies.vh_fortune_rebalance]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vh_fortune_rebalance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vh_fortune_rebalance]]
    modId="the_vault"
    mandatory=true
    versionRange="[1.18.2-3.15,)"
    ordering="AFTER"
    side="BOTH"
